# Generated by Django 2.0.2 on 2018-03-04 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxi_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxis', to=settings.AUTH_USER_MODEL),
        ),
    ]
