# Generated by Django 2.0.2 on 2018-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180304_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Malo'), (2, 'Regular'), (3, 'Bueno')], default=2),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Amarillo'), (2, 'Blanco')], default=1),
        ),
    ]
