# Generated by Django 2.0.2 on 2018-03-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180309_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorTaxi',
        ),
    ]
