# Generated by Django 2.0.2 on 2018-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_colortaxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='comentario',
            field=models.TextField(max_length=255),
        ),
    ]
