# Generated by Django 2.0.2 on 2018-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taxi_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='numero',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
