# Generated by Django 2.0.2 on 2018-03-09 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180309_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxi',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
