# Generated by Django 2.0.2 on 2018-03-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180309_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi',
            name='creado',
        ),
    ]
