# Generated by Django 2.0.2 on 2018-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_taxi_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='costo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
